legacyStops = 
[
  {
      "tourID": "1",
      "stopID": "101",
      "groupTitle": "Welcome",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Director's Welcome",
      "description": "NULL",
      "speaker": "Karen Brosius",
      "speakerImage": " Executive Director",
      "source": "3"
  },
  {
      "tourID": "1",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Speical Exhibition Design",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "1",
      "title": "Sponsor",
      "description": "NULL",
      "speaker": "Lou Kennedy",
      "speakerImage": " CEO Nephron Pharmaceuticals",
      "source": "3-video"
  },
  {
      "tourID": "1",
      "stopID": "102",
      "groupTitle": "Introduction",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Introduction",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1-video"
  },
  {
      "tourID": "1",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Improvisation &amp; Jazz",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "1",
      "title": "Moving Image Research Collection",
      "description": "NULL",
      "speaker": "Greg Wilsbacher; Curator",
      "speakerImage": " Newsfilm Collections",
      "source": "5-video"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "Jazz in Japan",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Importing Jazz",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Jazz in Japan",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2-video"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Traditional Japanese Music",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "3",
      "title": "Shakuhachi Music",
      "description": "NULL",
      "speaker": "Choshi Or Shirabe",
      "speakerImage": "4",
      "source": "p02_m"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "5",
      "stopType": "5",
      "title": "Komuso Priest",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "film-10",
      "source": "film-10"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "6",
      "stopType": "4",
      "title": "Monks Playing Shakuhachi Flute",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "2",
      "source": "p02_i-1"
  },
  {
      "tourID": "1",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "7",
      "stopType": "4",
      "title": "Shakuhachi Flute",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "2",
      "source": "p02_i-2"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "Origins & Approaches to Jazz",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "American &amp; Japanese Approaches to Jazz",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "Jelly Roll Blues",
      "description": "NULL",
      "speaker": "Jelly Roll Morton",
      "speakerImage": "NULL",
      "source": "p04_m"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "4",
      "title": "Jelly Roll Blues Cover",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "p04_i"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "5",
      "stopType": "2",
      "title": "Origins of Jazz",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "6",
      "stopType": "3",
      "title": "Maple Leaf Rag",
      "description": "NULL",
      "speaker": "Scott Joplin",
      "speakerImage": "NULL",
      "source": "p05_m"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "7",
      "stopType": "4",
      "title": "Scott Joplin",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "p05_i-1"
  },
  {
      "tourID": "1",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "8",
      "stopType": "4",
      "title": "Maple Leaf Rag Poster",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "p05_i-2"
  },
  {
      "tourID": "1",
      "stopID": "105",
      "groupTitle": "Art Deco Animals",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Art Deco Animals",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "A National Dog",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "106",
      "groupTitle": "Natural Colors",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "107",
      "groupTitle": "Water",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "108",
      "groupTitle": "Women",
      "groupID": " Rebellion & Smoking",
      "stopType": "0",
      "title": "2",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "Victoria Cooke",
      "source": " Curator"
  },
  {
      "tourID": "1",
      "stopID": "109",
      "groupTitle": "A Cultured Home",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "110",
      "groupTitle": "Fashion of the Traditional Japanese Woman",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Kimonos",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "5",
      "title": "Kimono Fashion Show",
      "description": "NULL",
      "speaker": "Jun-30",
      "speakerImage": "film-4",
      "source": "film-4"
  },
  {
      "tourID": "1",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "5",
      "title": "Japanese Hair Styles",
      "description": "NULL",
      "speaker": "Apr-30",
      "speakerImage": "film-8",
      "source": "film-8"
  },
  {
      "tourID": "1",
      "stopID": "111",
      "groupTitle": "Japanese Jazz - A Classical Music",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "111",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Japanese Jazz - A Classical Music",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "111",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "Ragtime",
      "description": "NULL",
      "speaker": "Stravinsky",
      "speakerImage": "NULL",
      "source": "p06_m"
  },
  {
      "tourID": "1",
      "stopID": "112",
      "groupTitle": "Art Deco Fountains",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "113",
      "groupTitle": "Rice Cake Vendors",
      "groupID": "0",
      "stopType": "5",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Jun-29",
      "speakerImage": "film-5",
      "source": "film-5"
  },
  {
      "tourID": "1",
      "stopID": "114",
      "groupTitle": "Advertising",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "114",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Advertising",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "114",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "5",
      "title": "Street Advertisement for Shochiku Kinema",
      "description": "NULL",
      "speaker": "Mar-29",
      "speakerImage": "film-11",
      "source": "film-11"
  },
  {
      "tourID": "1",
      "stopID": "115",
      "groupTitle": "Smoking in Japanese Culture",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Smoking as a Motif",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Smoking in the Cultured Home",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "116",
      "groupTitle": "Fashion & Dance of the Modern Japanese Woman",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "116",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Fashion of the Modern Woman",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "116",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Japanese Sandman",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "116",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "3",
      "title": "Japanese Sandman",
      "description": "NULL",
      "speaker": "Paul Whiteman",
      "speakerImage": "NULL",
      "source": "p10_m"
  },
  {
      "tourID": "1",
      "stopID": "117",
      "groupTitle": "Butterfly of Nagasaki",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "117",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Butterfly of Nagasaki",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "117",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "Butterfly of Nagasaki",
      "description": "NULL",
      "speaker": "Watanabe Hamako",
      "speakerImage": "NULL",
      "source": "p11_m"
  },
  {
      "tourID": "1",
      "stopID": "117",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "4",
      "title": "Watanabe Hamako",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "p11_i"
  },
  {
      "tourID": "1",
      "stopID": "118",
      "groupTitle": "Dance ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "118",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "5",
      "title": "Singin' in the Rain",
      "description": "NULL",
      "speaker": "Jun-30",
      "speakerImage": "film-2",
      "source": "film-2"
  },
  {
      "tourID": "1",
      "stopID": "118",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "5",
      "title": "Native Dance",
      "description": "NULL",
      "speaker": "Jun-30",
      "speakerImage": "film-1",
      "source": "film-1"
  },
  {
      "tourID": "1",
      "stopID": "118",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "5",
      "title": "Japanese Chorus Girls",
      "description": "NULL",
      "speaker": "Jul-30",
      "speakerImage": "film-3",
      "source": "film-3"
  },
  {
      "tourID": "1",
      "stopID": "119",
      "groupTitle": "Hollywood and Japan",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "120",
      "groupTitle": "Japanese Prints",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "121",
      "groupTitle": "Oragami",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "122",
      "groupTitle": "The Modern Age",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Victoria Cooke",
      "speakerImage": " Curator",
      "source": "1"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "Additional Commentary on Jazz & Musical Selections",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Japanese Musical History",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "4",
      "title": "String Instrument from Nara",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "p03_i-1"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "4",
      "title": "Temple Bell",
      "description": " Fukuoka",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "2",
      "title": "Foreign Influence",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "5",
      "stopType": "3",
      "title": "Three Little Maids from School",
      "description": "NULL",
      "speaker": "Gilbert and Sullivan",
      "speakerImage": "NULL",
      "source": "p07_m"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "6",
      "stopType": "3",
      "title": "Miya sama",
      "description": " Miya sama",
      "speaker": "NULL",
      "speakerImage": "Gilbert and Sullivan",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "7",
      "stopType": "4",
      "title": "The Mikado",
      "description": " Three Little Maids",
      "speaker": "Lithograph depicts Kate Forster (left)",
      "speakerImage": " Geraldine Ulmar (center)",
      "source": " and Geraldine St. Maur (right) as the three little maids"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "8",
      "stopType": "2",
      "title": "Portraying the Exotic",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "9",
      "stopType": "3",
      "title": "La Boheme",
      "description": "NULL",
      "speaker": "Giacomo Puccini",
      "speakerImage": "NULL",
      "source": "p08_m"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "10",
      "stopType": "2",
      "title": "Madama Butterfly",
      "description": "NULL",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": "2"
  },
  {
      "tourID": "1",
      "stopID": "123",
      "groupTitle": "NULL",
      "groupID": "11",
      "stopType": "3",
      "title": "Madama Butterfly",
      "description": "NULL",
      "speaker": "Giacomo Puccini",
      "speakerImage": "NULL",
      "source": "p09_m"
  },
  {
      "tourID": "1",
      "stopID": "124",
      "groupTitle": "Additional Films from MIRC",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "1",
      "stopID": "124",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "5",
      "title": "Education in Japan (Silent)",
      "description": "NULL",
      "speaker": "1921",
      "speakerImage": "film-6",
      "source": "film-6"
  },
  {
      "tourID": "1",
      "stopID": "124",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "5",
      "title": "Ivory Carving (Silent)",
      "description": "NULL",
      "speaker": "1922",
      "speakerImage": "film-9",
      "source": "film-9"
  },
  {
      "tourID": "1",
      "stopID": "124",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "5",
      "title": "Bijinza Cabaret Young Girls Chorus",
      "description": "NULL",
      "speaker": "Dec-31",
      "speakerImage": "film-7",
      "source": "film-7"
  },
  {
      "tourID": "1",
      "stopID": "125",
      "groupTitle": "Sign up for our E-Newsletter",
      "groupID": "0",
      "stopType": "10",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "newsletter"
  },
  {
      "tourID": "2",
      "stopID": "201",
      "groupTitle": "Say Hello to Gladys",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "gladys-1",
      "source": "intro"
  },
  {
      "tourID": "2",
      "stopID": "202",
      "groupTitle": "Where is Japan?",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "gladys-2",
      "source": "japan"
  },
  {
      "tourID": "2",
      "stopID": "203",
      "groupTitle": "Song Books",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelly",
      "speakerImage": " Education Assistant",
      "source": "2"
  },
  {
      "tourID": "2",
      "stopID": "204",
      "groupTitle": "Poster of Books",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelly",
      "speakerImage": " Education Assistant",
      "source": "2"
  },
  {
      "tourID": "2",
      "stopID": "205",
      "groupTitle": "Skiiing is Fun!",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "skier"
  },
  {
      "tourID": "2",
      "stopID": "206",
      "groupTitle": "A Loyal Dog",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "akita"
  },
  {
      "tourID": "2",
      "stopID": "207",
      "groupTitle": "Swimming Fish",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "fish"
  },
  {
      "tourID": "2",
      "stopID": "208",
      "groupTitle": "Comfortable Kimono",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "kimono"
  },
  {
      "tourID": "2",
      "stopID": "209",
      "groupTitle": "King of the Jungle",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Scott Pfaff",
      "speakerImage": " Riverbanks Zoo",
      "source": "lions"
  },
  {
      "tourID": "2",
      "stopID": "210",
      "groupTitle": "Baby Turtles (Tortoises)",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Scott Pfaff",
      "speakerImage": " Riverbanks Zoo",
      "source": "turtles"
  },
  {
      "tourID": "2",
      "stopID": "211",
      "groupTitle": "Deep Sea Travel ",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelly",
      "speakerImage": " Education Assistant",
      "source": "3"
  },
  {
      "tourID": "2",
      "stopID": "212",
      "groupTitle": "The Rabbit in the Moon",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "rabbit"
  },
  {
      "tourID": "2",
      "stopID": "213",
      "groupTitle": "Crowned Cranes",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Scott Pfaff",
      "speakerImage": " Riverbanks Zoo",
      "source": "cranes"
  },
  {
      "tourID": "2",
      "stopID": "214",
      "groupTitle": "Thanks!",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Gladys the Grasshopper",
      "speakerImage": "1",
      "source": "out"
  },
  {
      "tourID": "3",
      "stopID": "301",
      "groupTitle": "Introduction",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "3",
      "stopID": "301",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Introduction to Meiji Magic",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "301",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "How to look at the pieces",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "302",
      "groupTitle": "Court Life",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "303",
      "groupTitle": "Festivals",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "304",
      "groupTitle": "The Wise Mother &amp; Tea Ceremonies",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "NULL"
  },
  {
      "tourID": "3",
      "stopID": "304",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "The Wise Mother",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "304",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "The Tea Ceremony",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "304",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "5",
      "title": "Tea Service Demonstrated (Silent)",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "film-12",
      "source": "film-12"
  },
  {
      "tourID": "3",
      "stopID": "305",
      "groupTitle": "Nature",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "3",
      "stopID": "306",
      "groupTitle": "Conclusion",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Alex Kasten",
      "speakerImage": " collector",
      "source": "1"
  },
  {
      "tourID": "4",
      "stopID": "101",
      "groupTitle": "Welcome",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Welcome",
      "description": "NULL",
      "speaker": "Karen Brosius",
      "speakerImage": " CMA Executive Director",
      "source": "karen"
  },
  {
      "tourID": "4",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Overview of Exhibition",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " CMA Chief Curator",
      "source": "will"
  },
  {
      "tourID": "4",
      "stopID": "102",
      "groupTitle": "Introduction",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Childhood Dreams",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Arresting Imagery",
      "description": "NULL",
      "speaker": "Nick Capasso",
      "speakerImage": " Director of the Fitchburg Art Museum",
      "source": "capasso"
  },
  {
      "tourID": "4",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Echoing the Past",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "103",
      "groupTitle": "Tiger",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Tiger",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "What's the Attraction?",
      "description": "NULL",
      "speaker": "Nick Capasso",
      "speakerImage": " Director of the Fitchburg Art Museum",
      "source": "capasso"
  },
  {
      "tourID": "4",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "4",
      "title": "Portrait of Mr. Van Amburgh",
      "description": " As He Appeared with His Animals at the London Theatres",
      "speaker": "NULL",
      "speakerImage": "Edwin Henry Landseer",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "104",
      "groupTitle": "Hound and Cockatoo | Limited Pallete",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Hounds and Cockatoo",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Limited Pallete",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "4",
      "title": "White Dog",
      "description": "NULL",
      "speaker": "Alexandre-Fran&#231;ois Desportes (1661&#8211;1743)",
      "speakerImage": "NULL",
      "source": "desportes_hound"
  },
  {
      "tourID": "4",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "4",
      "title": "Jan Weenix",
      "description": "NULL",
      "speaker": "A Still Life of Game with a Cockatoo",
      "speakerImage": "NULL",
      "source": "cockatoo"
  },
  {
      "tourID": "4",
      "stopID": "105",
      "groupTitle": "Caught in a Net",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Caught in a Net",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Obscure Old Masters",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Dust Bin of Art History",
      "description": "NULL",
      "speaker": "Nick Capasso",
      "speakerImage": " Director of the Fitchburg Art Museum",
      "source": "capasso"
  },
  {
      "tourID": "4",
      "stopID": "106",
      "groupTitle": "Tondos - Pretator/Prey",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "106",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Wolf",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "106",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Swan",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "107",
      "groupTitle": "Scale of Paintings",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "108",
      "groupTitle": "Evolution as Artist",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "109",
      "groupTitle": "Beauty and Botanicals",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Inspiration and Beauty",
      "description": "NULL",
      "speaker": "Nick Capasso",
      "speakerImage": " Director of the Fitchburg Art Museum",
      "source": "capasso"
  },
  {
      "tourID": "4",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Botanicals",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "110",
      "groupTitle": "Attacked by Hounds",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "111",
      "groupTitle": "Around a Fountain",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "112",
      "groupTitle": "In Dubious Battle",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Genesis of <em>In Dubious Battle</em>",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Expanding the Horizon",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Enevitability of Behavoir",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "2",
      "title": "Mystery",
      "description": "NULL",
      "speaker": "Nick Capasso",
      "speakerImage": " Director of the Fitchburg Art Museum",
      "source": "capasso"
  },
  {
      "tourID": "4",
      "stopID": "113",
      "groupTitle": "Combining Appropriations",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "113",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Appropriation",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "113",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Process",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "114",
      "groupTitle": "Bird Concert",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "114",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Bird Concert",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "114",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "John James Audubon",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "114",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "4",
      "title": "A Concert of Birds",
      "description": "NULL",
      "speaker": "Richard Earlom",
      "speakerImage": "NULL",
      "source": "bird-concert"
  },
  {
      "tourID": "4",
      "stopID": "115",
      "groupTitle": "Interpreted Animals | In the Shadows",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "4",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Interpreted Animals",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "In the Shadows",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "116",
      "groupTitle": "Ribonned Fruit and Ribboned Flowers ",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "117",
      "groupTitle": "On the Wall",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "4",
      "stopID": "118",
      "groupTitle": "Conclusion",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "5",
      "stopID": "201",
      "groupTitle": "Introduction",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "5",
      "stopID": "201",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Gladys",
      "description": "NULL",
      "speaker": "Gladys",
      "speakerImage": "gladys",
      "source": "intro"
  },
  {
      "tourID": "5",
      "stopID": "201",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Music!",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "intro-music"
  },
  {
      "tourID": "5",
      "stopID": "202",
      "groupTitle": "Tigers",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "gladys"
  },
  {
      "tourID": "5",
      "stopID": "203",
      "groupTitle": "Elephants",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "203",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Elephants at the Zoo",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "203",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Elephant in Music",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "elephant-music"
  },
  {
      "tourID": "5",
      "stopID": "204",
      "groupTitle": "Farm",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "205",
      "groupTitle": "Lorikeets",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "206",
      "groupTitle": "Kangaroo",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "206",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Kangaroos at the Zoo",
      "description": "NULL",
      "speaker": "Susan O'Cain",
      "speakerImage": " Riverbanks Zoo",
      "source": "susan"
  },
  {
      "tourID": "5",
      "stopID": "206",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Kangaroos in Music",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "kangaroo-music"
  },
  {
      "tourID": "5",
      "stopID": "207",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Mrs. Shelley's Pet",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "5",
      "stopID": "207",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Turtles",
      "description": "NULL",
      "speaker": "Scott Pfaff",
      "speakerImage": "scott",
      "source": "turtles"
  },
  {
      "tourID": "5",
      "stopID": "207",
      "groupTitle": "Turtles and Mrs. Shelley's Pet",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "5",
      "stopID": "208",
      "groupTitle": "Swan Music",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "swan-music"
  },
  {
      "tourID": "5",
      "stopID": "209",
      "groupTitle": "Painting is Fun!",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Shelley Reed",
      "speakerImage": " Artist",
      "source": "shelley"
  },
  {
      "tourID": "5",
      "stopID": "210",
      "groupTitle": "Lions",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "5",
      "stopID": "210",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "King of the Jungle",
      "description": "NULL",
      "speaker": "Scott Pfaff",
      "speakerImage": "scott",
      "source": "lions"
  },
  {
      "tourID": "5",
      "stopID": "210",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Lion Music",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "lion-music"
  },
  {
      "tourID": "5",
      "stopID": "211",
      "groupTitle": "Bird Concert",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "bird-concert"
  },
  {
      "tourID": "5",
      "stopID": "212",
      "groupTitle": "Rooster and Turkey Music",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Danielle Kelley",
      "speakerImage": "danielle",
      "source": "roosterandturkey-music"
  },
  {
      "tourID": "6",
      "stopID": "101",
      "groupTitle": "Welcome",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Welcome",
      "description": "NULL",
      "speaker": "Karen Brosius",
      "speakerImage": " CMA Executive Director",
      "source": "karen"
  },
  {
      "tourID": "6",
      "stopID": "101",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Presenting Sponsor Welcome",
      "description": "NULL",
      "speaker": "Frank Brunson",
      "speakerImage": " Mayor of Forest Acres",
      "source": "fa-mayor"
  },
  {
      "tourID": "6",
      "stopID": "102",
      "groupTitle": "Introduction",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Overview of Exhibition",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " CMA Chief Curator",
      "source": "will"
  },
  {
      "tourID": "6",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "Stockbridge",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "1.4",
      "source": "1.4"
  },
  {
      "tourID": "6",
      "stopID": "103",
      "groupTitle": "The Art Critic",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " CMA Chief Curator",
      "source": "will"
  },
  {
      "tourID": "6",
      "stopID": "104",
      "groupTitle": "Life of Rockwell",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "American Chronicles 1",
      "description": "length: 5:30",
      "speaker": "American Chronicles",
      "speakerImage": "2.1",
      "source": "2.1"
  },
  {
      "tourID": "6",
      "stopID": "104",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "1",
      "title": "American Chronicles 2",
      "description": "length: 6:18",
      "speaker": "American Chronicles",
      "speakerImage": "2.2",
      "source": "2.2"
  },
  {
      "tourID": "6",
      "stopID": "105",
      "groupTitle": "Day In the Life of a Little Girl",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Mary Wahlen",
      "speakerImage": " Rockwell Model",
      "source": "4.1"
  },
  {
      "tourID": "6",
      "stopID": "106",
      "groupTitle": "Girl at the Mirror",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Mary Whalen",
      "speakerImage": " Rockwell Model",
      "source": "5.1"
  },
  {
      "tourID": "6",
      "stopID": "107",
      "groupTitle": "Civil Rights",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " CMA Chief Curator",
      "source": "will"
  },
  {
      "tourID": "6",
      "stopID": "108",
      "groupTitle": "The Problem We All Live With",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Rockwell capturing",
      "description": "NULL",
      "speaker": "Ruby Bridges Hall",
      "speakerImage": " Civil Rights Activist",
      "source": "8.1"
  },
  {
      "tourID": "6",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Not Afraid",
      "description": "NULL",
      "speaker": "Ruby Bridges Hall",
      "speakerImage": " Civil Rights Activist",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Parent & Teacher",
      "description": "NULL",
      "speaker": "Ruby Bridges Hall",
      "speakerImage": " Civil Rights Activist",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "109",
      "groupTitle": "New Kids in the Neighborhood",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "1",
      "title": "Wray Gunn",
      "description": "NULL",
      "speaker": "Wray Gunn",
      "speakerImage": " Rockwell Model",
      "source": "9.1"
  },
  {
      "tourID": "6",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Rockwell's Process",
      "description": "NULL",
      "speaker": "Wray Gunn",
      "speakerImage": " Rockwell Model",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "2",
      "title": "Rockwell as a person",
      "description": "NULL",
      "speaker": "Wray Gunn",
      "speakerImage": " Rockwell Model",
      "source": "NULL"
  },
  {
      "tourID": "6",
      "stopID": "109",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "2",
      "title": "Cat story",
      "description": "NULL",
      "speaker": "Wray Gunn",
      "speakerImage": " Rockwell Model",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "102",
      "groupTitle": "Shadow Decoration ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "101",
      "groupTitle": "Director's Welcome",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "Karen Brosius",
      "speakerImage": " Executive Director",
      "source": "karen"
  },
  {
      "tourID": "7",
      "stopID": "106",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "The Goldfish ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "106",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "The Goldfish ",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "106",
      "groupTitle": "The Goldfish ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "<em>Sirens</em> from Nocturnes ",
      "description": "",
      "speaker": "Claude Debussy",
      "speakerImage": "",
      "source": "5.2"
  },
  {
      "tourID": "7",
      "stopID": "105",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Sirens ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "105",
      "groupTitle": "Sirens ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "104",
      "groupTitle": "Evening Illuminations at the Paris Exposition",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "4",
      "title": "Luxembourg Gardens (today)",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "3.2"
  },
  {
      "tourID": "7",
      "stopID": "103",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "In the Luxembourg",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "103",
      "groupTitle": "Luxembourg ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "4",
      "title": "Jean-Francois Millet: Gleaners ",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "2.2"
  },
  {
      "tourID": "7",
      "stopID": "102",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Shadow Decoration ",
      "description": "NULL",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "106",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "3",
      "title": "Poissons d'or (<em>Goldfish</em>) from Images II ",
      "description": "",
      "speaker": "Claude Debussy",
      "speakerImage": "",
      "source": "6.3"
  },
  {
      "tourID": "7",
      "stopID": "107",
      "groupTitle": "Antiques Road Show ",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "Portrait of Miss Honor Woulfe Antiques Road Show Clip ",
      "speakerImage": "",
      "source": "7.1"
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "East End of the Grand Basin ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "East End of the Grand Basin ",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "East End of the Grand Basin ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "6",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "",
      "source": "8.3"
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "3",
      "title": "Symphony No. 9 ('From the New World')",
      "description": " mvt. II ",
      "speaker": "",
      "speakerImage": "Anton&iacute;n Dvo_&aacute;k",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "108",
      "groupTitle": "NULL",
      "groupID": "5",
      "stopType": "4",
      "title": "Great Basin of Chicago Worlds Fair 1893 ",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "",
      "source": "8.5"
  },
  {
      "tourID": "7",
      "stopID": "109",
      "groupTitle": "Girl in the Window Seat ",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "110",
      "groupTitle": "At The Piano ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "At The Piano ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "Foreign Lands and People from Kinderszenen ",
      "description": "",
      "speaker": "Robert Schumann",
      "speakerImage": "",
      "source": "10.2"
  },
  {
      "tourID": "7",
      "stopID": "110",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "3",
      "title": "Piano Sonata No. 32",
      "description": " Op. 111",
      "speaker": " mvt. 1 ",
      "speakerImage": "",
      "source": "Ludwig van Beethoven"
  },
  {
      "tourID": "7",
      "stopID": "111",
      "groupTitle": "An Alcove in the Art Students' League ",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "112",
      "groupTitle": "Lotus Lillies ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Lotus Lillies ",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "Lotus Lillies ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "6",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "",
      "source": "12.3"
  },
  {
      "tourID": "7",
      "stopID": "112",
      "groupTitle": "NULL",
      "groupID": "4",
      "stopType": "2",
      "title": "Clair de lune (Moonlight) ",
      "description": "",
      "speaker": "Claude Debussy",
      "speakerImage": "",
      "source": "12.4"
  },
  {
      "tourID": "7",
      "stopID": "113",
      "groupTitle": "The Golden Profile ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "113",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "The Golden Profile ",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "113",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "2",
      "title": "The Golden Profile ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "113",
      "groupTitle": "NULL",
      "groupID": "3",
      "stopType": "3",
      "title": "<em>The Girl with the Flaxen Hair</em> from Preludes I ",
      "description": "",
      "speaker": "Claude Debussy",
      "speakerImage": "",
      "source": "13.3"
  },
  {
      "tourID": "7",
      "stopID": "114",
      "groupTitle": "On The Heights ",
      "groupID": "0",
      "stopType": "2",
      "title": "NULL",
      "description": "",
      "speaker": "Will South",
      "speakerImage": " Chief Curator",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "115",
      "groupTitle": "Morning Clouds Over Mountaintop ",
      "groupID": "0",
      "stopType": "0",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "NULL",
      "source": "NULL"
  },
  {
      "tourID": "7",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "1",
      "stopType": "2",
      "title": "Morning Clouds Over Mountaintop ",
      "description": "",
      "speaker": "Peter Hoyt",
      "speakerImage": " Adjunct Curator of Music",
      "source": ""
  },
  {
      "tourID": "7",
      "stopID": "115",
      "groupTitle": "NULL",
      "groupID": "2",
      "stopType": "3",
      "title": "Clouds from Nocturnes ",
      "description": "",
      "speaker": "Claude Debussy",
      "speakerImage": "",
      "source": "15.2"
  },
  {
      "tourID": "8",
      "stopID": "201",
      "groupTitle": "Shadow Decoration",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "1",
      "source": "1"
  },
  {
      "tourID": "8",
      "stopID": "202",
      "groupTitle": "Afternoon in the Cluny Garden",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "2",
      "source": "2"
  },
  {
      "tourID": "8",
      "stopID": "203",
      "groupTitle": "The Red Balloon",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "NULL",
      "speaker": "NULL",
      "speakerImage": "3",
      "source": "3"
  },
  {
      "tourID": "8",
      "stopID": "204",
      "groupTitle": "The Goldfish",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "4",
      "source": "4"
  },
  {
      "tourID": "8",
      "stopID": "205",
      "groupTitle": "Mumbley-peg",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "5",
      "source": "5"
  },
  {
      "tourID": "8",
      "stopID": "206",
      "groupTitle": "On the Porch",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "6",
      "source": "6"
  },
  {
      "tourID": "8",
      "stopID": "207",
      "groupTitle": "Palette",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "7",
      "source": "7"
  },
  {
      "tourID": "8",
      "stopID": "208",
      "groupTitle": "Peonies",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "8",
      "source": "8"
  },
  {
      "tourID": "8",
      "stopID": "209",
      "groupTitle": "A Corner of Grandmother's Garden",
      "groupID": "0",
      "stopType": "1",
      "title": "NULL",
      "description": "",
      "speaker": "NULL",
      "speakerImage": "9",
      "source": "9"
  }
]

convertTour = (data) ->
  _.chain(data)
    .groupBy('tourID')
    .map((tour)->
      tourStops = 
        _.chain(tour)
          .groupBy('stopID')
          .map( (stop) ->
            if stop.length > 1 # Is a group
              childStops = 
                _.chain(stop)
                  .sortBy('groupID')
                  .filter( (childStop, i) -> return i > 0)
                  .map( (childStop) ->
                    'title': childStop.title.trim()
                    'speaker': childStop.speaker.trim()
                    'media': childStop.source
                    'stopType': +childStop.stopType            
                    )
                  .value()
              {
                'type': 0
                'stopID': +stop[0].stopID
                'title': stop[0].groupTitle.trim()
                'childStops': childStops
              }
            else
              {
                'type': 1
                'stopID': +stop[0].stopID
                'title': stop[0].groupTitle.trim()
                'speaker': stop[0].speaker.trim()
                'media': stop[0].source
                'stopType': +stop[0].stopType
              }
          )
          .value()
      'tourID': +tour[0].tourID
      'stops': tourStops
    )
    .value()

console.log convertTour(legacyStops)
    